project(Game)

add_library(Game SHARED
    Camera/anicamera/AniCamera.cpp
    Camera/anicamera/AniCamera.h
    Camera/arenacamera/ArenaCamera.cpp
    Camera/arenacamera/ArenaCamera.h
    Camera/basecamera/BaseCamera.cpp
    Camera/basecamera/BaseCamera.h
    Camera/basecamera/CamerasBlender.h
    Camera/camera_inc.h
    Camera/cameracontroller/CameraController.cpp
    Camera/cameracontroller/CameraController.h
    Camera/cameracontroller/ICameraController.h
    Camera/camerashocker/CameraShocker.cpp
    Camera/camerashocker/CameraShocker.h
    Camera/charactercamera/CharacterCamera.cpp
    Camera/charactercamera/CharacterCamera.h
    Camera/cutscenecamera/CutSceneCamera.cpp
    Camera/cutscenecamera/CutSceneCamera.h
    Camera/fixedcamera/FixedCamera.cpp
    Camera/fixedcamera/FixedCamera.h
    Camera/freecamera/FreeCamera.cpp
    Camera/freecamera/FreeCamera.h
    Camera/postprocess/filters/BlackAndWhite.cpp
    Camera/postprocess/filters/BlackAndWhite.h
    Camera/postprocess/filters/Blur.cpp
    Camera/postprocess/filters/Blur.h
    Camera/postprocess/filters/MotionBlur.cpp
    Camera/postprocess/filters/MotionBlur.h
    Camera/postprocess/filters/MotionEffect.cpp
    Camera/postprocess/filters/MotionEffect.h
    Camera/postprocess/filters/Splash.cpp
    Camera/postprocess/filters/Splash.h
    Camera/postprocess/PostProcess.cpp
    Camera/postprocess/PostProcess.h
    Camera/pvpcamera/PvPCamera.cpp
    Camera/pvpcamera/PvPCamera.h
    Camera/rotatedcamera/RotatedCamera.cpp
    Camera/rotatedcamera/RotatedCamera.h
    Camera/splashmanager/SplashManager.cpp
    Camera/splashmanager/SplashManager.h
    Camera/staticcamera/StaticCamera.cpp
    Camera/staticcamera/StaticCamera.h
    Camera/trackcamera/CameraTracksFile.h
    Camera/trackcamera/PathTracks.cpp
    Camera/trackcamera/PathTracks.h
    Camera/trackcamera/TrackCamera.cpp
    Camera/trackcamera/TrackCamera.h
    Camera/trackcamera/TrackCameraED.cpp
    Camera/trackcamera/TrackCameraED.h
    CoolThings/achievements/Achievements.cpp
    CoolThings/achievements/Achievements.h
    CoolThings/achievements/Bosses.cpp
    CoolThings/achievements/Land.cpp
    CoolThings/achievements/Sea.cpp
    CoolThings/activeobject/ActiveObject.cpp
    CoolThings/activeobject/ActiveObject.h
    CoolThings/animatedmodel/AnimatedModel.cpp
    CoolThings/animatedmodel/AnimatedModel.h
    CoolThings/animatedmodel/AnimatedModelsArbiter.cpp
    CoolThings/animatedmodel/AnimatedModelsArbiter.h
    CoolThings/animatedmodel/Shell.h
    CoolThings/animatedmodel/Track.cpp
    CoolThings/animatedmodel/Track.h
    CoolThings/anxcounter/AnxCounter.cpp
    CoolThings/anxcounter/AnxCounter.h
    CoolThings/bonuses/BonusesManagerImp.cpp
    CoolThings/bonuses/BonusesManagerImp.h
    CoolThings/bonuses/BonusesModelsManager.cpp
    CoolThings/bonuses/BonusesModelsManager.h
    CoolThings/bonuses/BonusesTable.cpp
    CoolThings/bonuses/BonusesTable.h
    CoolThings/cacheservice/CacheService.cpp
    CoolThings/cacheservice/CacheService.h
    CoolThings/cannonball/cannonBall.cpp
    CoolThings/cannonball/cannonBall.h
    CoolThings/cloudsmap/CloudsMap.cpp
    CoolThings/cloudsmap/CloudsMap.h
    CoolThings/console/Console.cpp
    CoolThings/console/Console.h
    CoolThings/console/SimpleParser.h
    CoolThings/damageeffect/DamageEffect.cpp
    CoolThings/damageeffect/DamageEffect.h
    CoolThings/flares/Flares.cpp
    CoolThings/flares/Flares.h
    CoolThings/flares/FlaresManager.cpp
    CoolThings/flares/FlaresManager.h
    CoolThings/flyer/Flyer.cpp
    CoolThings/flyer/Flyer.h
    CoolThings/flyerscloud/FlyersCloud.cpp
    CoolThings/flyerscloud/FlyersCloud.h
    CoolThings/flymanager/Fly.cpp
    CoolThings/flymanager/Fly.h
    CoolThings/flymanager/FlyManager.cpp
    CoolThings/flymanager/FlyManager.h
    CoolThings/grass/Generator.cpp
    CoolThings/grass/Grass.cpp
    CoolThings/grass/Grass.h
    CoolThings/grass/GrassExecutor.cpp
    CoolThings/hint/hint.cpp
    CoolThings/hint/hint.h
    CoolThings/joysticktrigger/JoystickTrigger.cpp
    CoolThings/joysticktrigger/JoystickTrigger.h
    CoolThings/lights/AmbientLight.cpp
    CoolThings/lights/AmbientLight.h
    CoolThings/lights/DirectionLight.cpp
    CoolThings/lights/DirectionLight.h
    CoolThings/lights/Light.cpp
    CoolThings/lights/Light.h
    CoolThings/lights/LightPoint.cpp
    CoolThings/lights/LightPoint.h
    CoolThings/localeffect/LocalEffect.cpp
    CoolThings/localeffect/LocalEffect.h
    CoolThings/missiontimecalculator/MissionTimeCalculator.cpp
    CoolThings/missiontimecalculator/MissionTimeCalculator.h
    CoolThings/multiplayertrigger/MultiplayerTrigger.cpp
    CoolThings/multiplayertrigger/MultiplayerTrigger.h
    CoolThings/multiplayertrigger/UserCheckerService.cpp
    CoolThings/multiplayertrigger/UserCheckerService.h
    CoolThings/objecttip/ObjectTip.cpp
    CoolThings/objecttip/ObjectTip.h
    CoolThings/posteffects/Common.h
    CoolThings/posteffects/Filters/DoF.cpp
    CoolThings/posteffects/Filters/DoF.h
    CoolThings/posteffects/Filters/Glow.cpp
    CoolThings/posteffects/Filters/Glow.h
    CoolThings/posteffects/Filters/RadialBlur.cpp
    CoolThings/posteffects/Filters/RadialBlur.h
    CoolThings/posteffects/Filters/Sharpness.cpp
    CoolThings/posteffects/Filters/Sharpness.h
    CoolThings/posteffects/PostEffects.cpp
    CoolThings/posteffects/PostEffects.h
    CoolThings/posteffects/UberFilter.cpp
    CoolThings/posteffects/UberFilter.h
    CoolThings/pssm/pssm.cpp
    CoolThings/pssm/pssm.h
    CoolThings/quitobject/QuitObject.cpp
    CoolThings/quitobject/QuitObject.h
    CoolThings/rain/rain.cpp
    CoolThings/rain/rain.h
    CoolThings/shadowmap/pcsmwtrastc.cpp
    CoolThings/shadowmap/pcsmwtrastc.h
    CoolThings/shadowmap/shadowsserv.cpp
    CoolThings/shadowmap/shadowsserv.h
    CoolThings/shootermg/AnimBlender.cpp
    CoolThings/shootermg/AnimBlender.h
    CoolThings/shootermg/AnimHandler.cpp
    CoolThings/shootermg/AnimHandler.h
    CoolThings/shootermg/AnimListener.cpp
    CoolThings/shootermg/AnimListener.h
    CoolThings/shootermg/Minigun.cpp
    CoolThings/shootermg/Minigun.h
    CoolThings/shootermg/physic.h
    CoolThings/shootermg/Shooter.cpp
    CoolThings/shootermg/Shooter.h
    CoolThings/shootermg/ShooterEffect.cpp
    CoolThings/shootermg/ShooterEffect.h
    CoolThings/shootermg/ShooterKickOut.cpp
    CoolThings/shootermg/ShooterKickOut.h
    CoolThings/shootermg/ShooterTargets.cpp
    CoolThings/shootermg/ShooterTargets.h
    # CoolThings/SndConverter/SndConverter.cpp
    # CoolThings/SndConverter/SndConverter.h
    CoolThings/stainkiller/StainKiller.cpp
    CoolThings/stainkiller/StainKiller.h
    CoolThings/stainmanager/StainManager.cpp
    CoolThings/stainmanager/StainManager.h
    # CoolThings/stalactite/Stalactite.cpp
    # CoolThings/stalactite/Stalactite.h
    CoolThings/sunglow/SunGlow.cpp
    CoolThings/sunglow/SunGlow.h
    CoolThings/TextureMapper/TextureMapper.cpp
    CoolThings/TextureMapper/TextureMapper.h
    CoolThings/trailer/Trailer.cpp
    CoolThings/trailer/Trailer.h
    CoolThings/trailmanager/register/register.cpp
    CoolThings/trailmanager/register/register.h
    CoolThings/trailmanager/Trail.cpp
    CoolThings/trailmanager/Trail.h
    CoolThings/trailmanager/TrailManager.cpp
    CoolThings/trailmanager/TrailManager.h
    CoolThings/trailparams/TrailParams.cpp
    CoolThings/trailparams/TrailParams.h
    CoolThings/traps/flamethrower/flamethrower.cpp
    CoolThings/traps/flamethrower/flamethrower.h
    CoolThings/traps/flamethrower/flamethrowerpattern.cpp
    CoolThings/traps/flamethrower/flamethrowerpattern.h
    CoolThings/traps/thorn/thorn.cpp
    CoolThings/traps/thorn/thorn.h
    CoolThings/traps/thorn/thornpattern.cpp
    CoolThings/traps/thorn/thornpattern.h
    CoolThings/traps/trapbase.cpp
    CoolThings/traps/trapbase.h
    CoolThings/vibrator/Vibrator.cpp
    CoolThings/vibrator/Vibrator.h
    CoolThings/videoplayer/videoplayer.cpp
    CoolThings/videoplayer/videoplayer.h
    CoolThings/waterfoam/waterfoam.cpp
    CoolThings/watertrails/TrackService.cpp
    CoolThings/watertrails/TrackService.h
    CoolThings/watertrails/WaterTrack.cpp
    CoolThings/watertrails/WaterTrack.h
    CoolThings/weather/Fog.cpp
    CoolThings/weather/Fog.h
    CoolThings/weather/Sky.cpp
    CoolThings/weather/Sky.h
    CoolThings/weather/Weather.cpp
    CoolThings/weather/Weather.h
    CoolThings/weather/Wind.cpp
    CoolThings/weather/Wind.h
    Interface/circularbar/CircularBar.cpp
    Interface/circularbar/CircularBar.h
    Interface/combopreview/ComboPreview.cpp
    Interface/combopreview/ComboPreview.h
    Interface/gameui/BaseGUICursor.cpp
    Interface/gameui/BaseGUICursor.h
    Interface/gameui/BaseGUIElement.cpp
    Interface/gameui/BaseGUIElement.h
    Interface/gameui/BaseGUITable.cpp
    Interface/gameui/BaseGUITable.h
    Interface/gameui/BaseGUIText.cpp
    Interface/gameui/BaseGUIText.h
    Interface/gameui/GUIButton.cpp
    Interface/gameui/GUIButton.h
    Interface/gameui/GUICharacter.cpp
    Interface/gameui/GUICharacter.h
    Interface/gameui/GUIEventWatcher.cpp
    Interface/gameui/GUIEventWatcher.h
    Interface/gameui/GUIList.cpp
    Interface/gameui/GUIList.h
    Interface/gameui/GUIPanel.cpp
    Interface/gameui/GUIPanel.h
    Interface/gameui/GUISelector.cpp
    Interface/gameui/GUISelector.h
    Interface/gameui/GUISlider.cpp
    Interface/gameui/GUISlider.h
    Interface/gameui/GUITable.cpp
    Interface/gameui/GUITable.h
    Interface/gameui/GUIWidget.cpp
    Interface/gameui/GUIWidget.h
    Interface/gameui/render/QuadRender.cpp
    Interface/gameui/render/QuadRender.h
    Interface/progress/Progress.cpp
    Interface/progress/Progress.h
    Interface/progressbar/csProgressBar.cpp
    Interface/progressbar/csProgressBar.h
    Interface/taskpointer/TaskPointer.cpp
    Interface/taskpointer/TaskPointer.h
    Interface/taskviewer/TaskViewer.cpp
    Interface/taskviewer/TaskViewer.h
    Interface/utils/InterfaceUtils.cpp
    Interface/utils/InterfaceUtils.h
    Mission/CAPROFAPI.h
    Mission/IMissionsManagerService.h
    Mission/Mission.cpp
    Mission/Mission.h
    Mission/MissionLoader.cpp
    Mission/MissionLoader.h
    Mission/MissionObjectsList.cpp
    Mission/MissionObjectsList.h
    Mission/MissionProfiler.cpp
    Mission/MissionProfiler.h
    Mission/MissionsManager.cpp
    Mission/MissionsManager.h
    Mission/objects/AcceptDetector.cpp
    Mission/objects/AcceptDetector.h
    Mission/objects/ActivateTrigger.cpp
    Mission/objects/ActivateTrigger.h
    Mission/objects/AliveDetector.cpp
    Mission/objects/AliveDetector.h
    Mission/objects/Balancer.cpp
    Mission/objects/Balancer.h
    Mission/objects/CollisionBox.cpp
    Mission/objects/CollisionBox.h
    Mission/objects/ControlTrigger.cpp
    Mission/objects/ControlTrigger.h
    Mission/objects/ConvexAreaDetector.cpp
    Mission/objects/ConvexAreaDetector.h
    Mission/objects/Counter.cpp
    Mission/objects/Counter.h
    Mission/objects/DamageDetector.cpp
    Mission/objects/DamageDetector.h
    Mission/objects/Delay.cpp
    Mission/objects/Delay.h
    Mission/objects/Fader.cpp
    Mission/objects/Fader.h
    Mission/objects/GamerProfile.cpp
    Mission/objects/GamerProfile.h
    Mission/objects/Inverter.cpp
    Mission/objects/Inverter.h
    Mission/objects/LiveWatcher.cpp
    Mission/objects/LiveWatcher.h
    Mission/objects/LoadingTrigger.cpp
    Mission/objects/LoadingTrigger.h
    Mission/objects/LogicSwitcher.cpp
    Mission/objects/LogicSwitcher.h
    Mission/objects/Mission3DSound.cpp
    Mission/objects/Mission3DSound.h
    Mission/objects/MissionEnvSound.cpp
    Mission/objects/MissionEnvSound.h
    Mission/objects/MissionGeometry.cpp
    Mission/objects/MissionGeometry.h
    Mission/objects/MissionLocator.cpp
    Mission/objects/MissionLocator.h
    Mission/objects/MissionMusic.cpp
    Mission/objects/MissionMusic.h
    Mission/objects/MissionParticles.cpp
    Mission/objects/MissionParticles.h
    Mission/objects/MissionPhysObject.cpp
    Mission/objects/MissionPhysObject.h
    Mission/objects/MissionPhysObjPattern.cpp
    Mission/objects/MissionPhysObjPattern.h
    Mission/objects/MissionRandomSound.cpp
    Mission/objects/MissionRandomSound.h
    Mission/objects/MissionReloader.cpp
    Mission/objects/MissionReloader.h
    Mission/objects/MissionSoundBase.cpp
    Mission/objects/MissionSoundBase.h
    Mission/objects/MissionSoundEnvironment.cpp
    Mission/objects/MissionSoundEnvironment.h
    Mission/objects/MissionStarter.cpp
    Mission/objects/MissionStarter.h
    Mission/objects/MissionTime.cpp
    Mission/objects/MissionTime.h
    Mission/objects/MissionVolumeSound.cpp
    Mission/objects/MissionVolumeSound.h
    Mission/objects/MovieFrame.cpp
    Mission/objects/MovieFrame.h
    Mission/objects/MultiDelay.cpp
    Mission/objects/MultiDelay.h
    Mission/objects/ObjectsGroup.cpp
    Mission/objects/ObjectsGroup.h
    Mission/objects/PhysicObjLocator.cpp
    Mission/objects/PhysicObjLocator.h
    # Mission/objects/qttest/qttest.cpp
    # Mission/objects/qttest/qttest.h
    Mission/objects/RandomSelector.cpp
    Mission/objects/RandomSelector.h
    Mission/objects/RectDetector.cpp
    Mission/objects/RectDetector.h
    Mission/objects/SetLanguage.cpp
    Mission/objects/SetLanguage.h
    Mission/objects/SoundsManagment.cpp
    Mission/objects/SoundsManagment.h
    Mission/objects/SphereDetector.cpp
    Mission/objects/SphereDetector.h
    Mission/objects/StateAccessors.cpp
    Mission/objects/StateAccessors.h
    Mission/objects/SwingMachine.cpp
    Mission/objects/SwingMachine.h
    Mission/objects/Synchronizer.cpp
    Mission/objects/Synchronizer.h
    # Mission/objects/verlettest/Verlet.cpp
    # Mission/objects/verlettest/Verlet.h
    Mission/objects/WaterLevel.cpp
    Mission/objects/WaterLevel.h
    Mission/ObjectsFindManager.cpp
    Mission/ObjectsFindManager.h
)


set_target_properties(Game PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/modules
    LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/modules
    ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/modules
)

if(MSVC)
    target_compile_options(Game PRIVATE /wd4091)
endif()

target_compile_options(Game PRIVATE /Zc:forScope-)
